export default {
	// 会话
	sessions() {
		return [{
			id: 'a',
			tip: 99,
			avatar: '1.jpg',
			name: 'LindaLindaLindaLindaLindaLindaLindaLindaLindaLindaLindaLindaLindaLindaLindaLindaLindaLindaLindaLindaLinda',
			timeStamp: new Date(2020, 7, 25, 8, 13, 0),
			content: '你好呀ssssssssssssssssssssssssssssssssssssssssssssssssssssss！',
			topping: true
		}, {
			id: 'n',
			avatar: '5.jpg',
			name: '依依呀',
			timeStamp: new Date(2020, 3, 24, 7, 43, 0),
			content: '红红火火恍恍惚惚红红火火恍恍惚惚红红火火恍恍惚惚！'
		}, {
			id: 'd',
			avatar: '4.jpg',
			name: '皓皓',
			timeStamp: new Date(2020, 7, 23, 11, 3, 0),
			content: '啥时候还钱啊？',
			topping: false
		}, {
			id: 'b',
			tip: 22,
			avatar: '2.jpg',
			name: '猪小艾',
			timeStamp: new Date(2020, 7, 25, 6, 48, 0),
			content: '我发现一个好玩的地方哟，明天一起出去玩呗？',
			topping: true
		}, {
			id: 'c',
			tip: 1,
			avatar: '3.jpg',
			name: '苏研研',
			timeStamp: new Date(2020, 7, 24, 22, 23, 0),
			content: '小哥哥在干嘛呀，一起玩游戏嘛',
			topping: false
		}, {
			id: 'e',
			avatar: '5.jpg',
			name: '依依呀',
			timeStamp: new Date(2020, 3, 24, 7, 43, 0),
			content: '红红火火恍恍惚惚红红火火恍恍惚惚红红火火恍恍惚惚！',
			topping: false
		}, {
			id: 'f',
			avatar: '5.jpg',
			name: '依依呀',
			timeStamp: new Date(2020, 3, 24, 7, 43, 0),
			content: '红红火火恍恍惚惚红红火火恍恍惚惚红红火火恍恍惚惚！'
		}, {
			id: 'g',
			avatar: '5.jpg',
			name: '依依呀',
			timeStamp: new Date(2020, 3, 24, 7, 43, 0),
			content: '红红火火恍恍惚惚红红火火恍恍惚惚红红火火恍恍惚惚！'
		}, {
			id: 'h',
			avatar: '5.jpg',
			name: '依依呀',
			timeStamp: new Date(2020, 3, 24, 7, 43, 0),
			content: '红红火火恍恍惚惚红红火火恍恍惚惚红红火火恍恍惚惚！'
		}, {
			id: 'i',
			avatar: '5.jpg',
			name: '依依呀',
			timeStamp: new Date(2020, 3, 24, 7, 43, 0),
			content: '红红火火恍恍惚惚红红火火恍恍惚惚红红火火恍恍惚惚！'
		}, {
			id: 'j',
			avatar: '5.jpg',
			name: '依依呀',
			timeStamp: new Date(2020, 3, 24, 7, 43, 0),
			content: '红红火火恍恍惚惚红红火火恍恍惚惚红红火火恍恍惚惚！'
		}, {
			id: 'k',
			avatar: '5.jpg',
			name: '依依呀',
			timeStamp: new Date(2020, 3, 24, 7, 43, 0),
			content: '红红火火恍恍惚惚红红火火恍恍惚惚红红火火恍恍惚惚！'
		}, {
			id: 'l',
			avatar: '5.jpg',
			name: '依依呀',
			timeStamp: new Date(2020, 3, 24, 7, 43, 0),
			content: '红红火火恍恍惚惚红红火火恍恍惚惚红红火火恍恍惚惚！'
		}, {
			id: 'm',
			avatar: '5.jpg',
			name: '依依呀',
			timeStamp: new Date(2020, 3, 24, 7, 43, 0),
			content: '红红火火恍恍惚惚红红火火恍恍惚惚红红火火恍恍惚惚！'
		}]
	},
	// 好友分组
	groupings() {
		return [{
			id: 'a',
			name: '默认分组',
			friends: [{
				id: 'a',
				avatar: '1.jpg',
				nickname: 'Linda',
				noteName: '小姐姐',
				desc: '三生三世'
			}, {
				id: 'b',
				avatar: '2.jpg',
				nickname: '猪小艾',
				noteName: '',
				desc: 'vssvsvsvvssvsvsvvssvsvsvvssvsvsvvssvsvsvvssvsvsvvssvsvsvvssvsvsv'
			}]
		}, {
			id: 'b',
			name: '分组二',
			friends: [{
				id: 'c',
				avatar: '3.jpg',
				nickname: '苏研研',
				noteName: '',
				desc: '是飒飒撒发顺丰撒发生大萨达撒方式方法撒是飒飒撒发顺丰撒发生大萨达撒方式方法撒是飒飒撒发顺丰撒发生大萨达撒方式方法撒'
			}]
		}, {
			id: 'c',
			name: '分组三',
			friends: [{
				id: 'd',
				avatar: '4.jpg',
				nickname: '苏皓',
				noteName: '皓皓',
				desc: 'dsvfghjjhgdfs.....'
			}, {
				id: 'd',
				avatar: '4.jpg',
				nickname: '苏皓',
				noteName: '皓皓',
				desc: 'dsvfghjjhgdfs.....'
			}, {
				id: 'd',
				avatar: '4.jpg',
				nickname: '苏皓',
				noteName: '皓皓',
				desc: 'dsvfghjjhgdfs.....'
			}, {
				id: 'd',
				avatar: '4.jpg',
				nickname: '苏皓',
				noteName: '皓皓',
				desc: 'dsvfghjjhgdfs.....'
			}, {
				id: 'd',
				avatar: '4.jpg',
				nickname: '苏皓',
				noteName: '皓皓',
				desc: 'dsvfghjjhgdfs.....'
			}, {
				id: 'd',
				avatar: '4.jpg',
				nickname: '苏皓',
				noteName: '皓皓',
				desc: 'dsvfghjjhgdfs.....'
			}, {
				id: 'd',
				avatar: '4.jpg',
				nickname: '苏皓',
				noteName: '皓皓',
				desc: 'dsvfghjjhgdfs.....'
			}, {
				id: 'd',
				avatar: '4.jpg',
				nickname: '苏皓',
				noteName: '皓皓',
				desc: 'dsvfghjjhgdfs.....'
			}, {
				id: 'd',
				avatar: '4.jpg',
				nickname: '苏皓',
				noteName: '皓皓',
				desc: 'dsvfghjjhgdfs.....'
			}, {
				id: 'd',
				avatar: '4.jpg',
				nickname: '苏皓',
				noteName: '皓皓',
				desc: 'dsvfghjjhgdfs.....'
			}, {
				id: 'd',
				avatar: '4.jpg',
				nickname: '苏皓',
				noteName: '皓皓',
				desc: 'dsvfghjjhgdfs.....'
			}, {
				id: 'd',
				avatar: '4.jpg',
				nickname: '苏皓',
				noteName: '皓皓',
				desc: 'dsvfghjjhgdfs.....'
			}, {
				id: 'd',
				avatar: '4.jpg',
				nickname: '苏皓',
				noteName: '皓皓',
				desc: 'dsvfghjjhgdfs.....'
			}, {
				id: 'd',
				avatar: '4.jpg',
				nickname: '苏皓',
				noteName: '皓皓',
				desc: 'dsvfghjjhgdfs.....'
			}, {
				id: 'd',
				avatar: '4.jpg',
				nickname: '苏皓',
				noteName: '皓皓',
				desc: 'dsvfghjjhgdfs.....'
			}, {
				id: 'd',
				avatar: '4.jpg',
				nickname: '苏皓',
				noteName: '皓皓',
				desc: 'dsvfghjjhgdfs.....'
			}, {
				id: 'd',
				avatar: '4.jpg',
				nickname: '苏皓',
				noteName: '皓皓',
				desc: 'dsvfghjjhgdfs.....'
			}, {
				id: 'd',
				avatar: '4.jpg',
				nickname: '苏皓',
				noteName: '皓皓',
				desc: 'dsvfghjjhgdfs.....'
			}, {
				id: 'd',
				avatar: '4.jpg',
				nickname: '苏皓',
				noteName: '皓皓',
				desc: 'dsvfghjjhgdfs.....'
			}, {
				id: 'd',
				avatar: '4.jpg',
				nickname: '苏皓',
				noteName: '皓皓',
				desc: 'dsvfghjjhgdfs.....'
			}, {
				id: 'd',
				avatar: '4.jpg',
				nickname: '苏皓',
				noteName: '皓皓',
				desc: 'dsvfghjjhgdfs.....'
			}, {
				id: 'd',
				avatar: '4.jpg',
				nickname: '苏皓',
				noteName: '皓皓',
				desc: 'dsvfghjjhgdfs.....'
			}, {
				id: 'd',
				avatar: '4.jpg',
				nickname: '苏皓',
				noteName: '皓皓',
				desc: 'dsvfghjjhgdfs.....'
			}, {
				id: 'd',
				avatar: '4.jpg',
				nickname: '苏皓',
				noteName: '皓皓',
				desc: 'dsvfghjjhgdfs.....'
			}, {
				id: 'd',
				avatar: '4.jpg',
				nickname: '苏皓',
				noteName: '皓皓',
				desc: 'dsvfghjjhgdfs.....'
			}, {
				id: 'd',
				avatar: '4.jpg',
				nickname: '苏皓',
				noteName: '皓皓',
				desc: 'dsvfghjjhgdfs.....'
			}, {
				id: 'd',
				avatar: '4.jpg',
				nickname: '苏皓',
				noteName: '皓皓',
				desc: 'dsvfghjjhgdfs.....'
			}, {
				id: 'd',
				avatar: '4.jpg',
				nickname: '苏皓',
				noteName: '皓皓',
				desc: 'dsvfghjjhgdfs.....'
			}, {
				id: 'd',
				avatar: '4.jpg',
				nickname: '苏皓',
				noteName: '皓皓',
				desc: 'dsvfghjjhgdfs.....'
			}, {
				id: 'd',
				avatar: '4.jpg',
				nickname: '苏皓',
				noteName: '皓皓',
				desc: 'dsvfghjjhgdfs.....'
			}, {
				id: 'd',
				avatar: '4.jpg',
				nickname: '苏皓',
				noteName: '皓皓',
				desc: 'dsvfghjjhgdfs.....'
			}, {
				id: 'd',
				avatar: '4.jpg',
				nickname: '苏皓',
				noteName: '皓皓',
				desc: 'dsvfghjjhgdfs.....'
			}, {
				id: 'd',
				avatar: '4.jpg',
				nickname: '苏皓',
				noteName: '皓皓',
				desc: 'dsvfghjjhgdfs.....'
			}, {
				id: 'd',
				avatar: '4.jpg',
				nickname: '苏皓',
				noteName: '皓皓',
				desc: 'dsvfghjjhgdfs.....'
			}, {
				id: 'd',
				avatar: '4.jpg',
				nickname: '苏皓',
				noteName: '皓皓',
				desc: 'dsvfghjjhgdfs.....'
			}, {
				id: 'd',
				avatar: '4.jpg',
				nickname: '苏皓',
				noteName: '皓皓',
				desc: 'dsvfghjjhgdfs.....'
			}, {
				id: 'd',
				avatar: '4.jpg',
				nickname: '苏皓',
				noteName: '皓皓',
				desc: 'dsvfghjjhgdfs.....'
			}, {
				id: 'd',
				avatar: '4.jpg',
				nickname: '苏皓',
				noteName: '皓皓',
				desc: 'dsvfghjjhgdfs.....'
			}, {
				id: 'd',
				avatar: '4.jpg',
				nickname: '苏皓',
				noteName: '皓皓',
				desc: 'dsvfghjjhgdfs.....'
			}, {
				id: 'd',
				avatar: '4.jpg',
				nickname: '苏皓',
				noteName: '皓皓',
				desc: 'dsvfghjjhgdfs.....'
			}, {
				id: 'd',
				avatar: '4.jpg',
				nickname: '苏皓',
				noteName: '皓皓',
				desc: 'dsvfghjjhgdfs.....'
			}, {
				id: 'd',
				avatar: '4.jpg',
				nickname: '苏皓',
				noteName: '皓皓',
				desc: 'dsvfghjjhgdfs.....'
			}]
		}]
	},
	// 群组
	groups() {
		return [{
			id: 'a',
			name: 'OUZERO',
			avatar: '3.jpg',
			topping: true,
			founderId: 'o',
			isManager: true
		}, {
			id: 'b',
			name: '哈哈哈',
			avatar: '4.jpg',
			founderId: 'a',
			topping: true,
			isManager: false
		}, {
			id: 'c',
			name: '恍恍惚惚',
			avatar: '5.jpg',
			founderId: 'b',
			topping: false,
			isManager: true
		}]
	},
	// 聊天消息
	messages() {
		return [{
			id: 'o',
			type: 3,
			content: {
				voice: '',
				duration: 32
			},
			timeStamp: new Date(),
		}, {
			id: 'a',
			type: 3,
			content: {
				voice: '',
				duration: 60
			},
			timeStamp: new Date(),
		}, {
			id: 'o',
			type: 0,
			content: '啊哈哈哈哈？？？啊哈哈哈哈？？？啊哈哈哈哈？？？啊哈哈哈哈？？？啊哈哈哈哈？？？啊哈哈哈哈？？？',
			timeStamp: new Date() - 1000,
		}, {
			id: 'o',
			type: 1,
			content: '3.png',
			timeStamp: new Date() - 1000 * 60 * 60 * 2,
		}, {
			id: 'o',
			type: 1,
			content: '4.png',
			timeStamp: new Date() - 1000 * 60 * 60 * 2,
		}, {
			id: 'o',
			type: 0,
			content: '啊哈哈哈哈？？？啊哈哈哈哈？？？啊哈哈哈哈？？？啊哈哈哈哈？？？啊哈哈哈哈？？？啊哈哈哈哈？？？',
			timeStamp: new Date() - 1000 * 60,
		}, {
			id: 'a',
			type: 0,
			content: '红红火火恍恍惚惚红红火火恍恍惚惚红红火火恍恍惚惚红红火火恍恍惚惚红红火火恍恍惚惚红红火火恍恍惚惚',
			timeStamp: new Date() - 1000 * 60 * 60,
		}, {
			id: 'a',
			type: 0,
			content: '红红火火恍恍惚惚红红火火恍恍惚惚红红火火恍恍惚惚红红火火恍恍惚惚红红火火恍恍惚惚红红火火恍恍惚惚',
			timeStamp: new Date() - 1000 * 60 * 60 * 2,
		}, {
			id: 'a',
			type: 1,
			content: '1.jpg',
			timeStamp: new Date() - 1000 * 60 * 60 * 2,
		}, {
			id: 'a',
			type: 1,
			content: '2.png',
			timeStamp: new Date() - 1000 * 60 * 60 * 2,
		}, {
			id: 'o',
			type: 0,
			content: '咋啦？？？',
			timeStamp: new Date(2020, 7, 12, 17, 46, 0),
		}, {
			id: 'a',
			type: 0,
			content: '红红火火恍恍惚惚红红火火恍恍惚惚红红火火恍恍惚惚红红火火恍恍惚惚红红火火恍恍惚惚红红火火恍恍惚惚',
			timeStamp: new Date(2020, 7, 12, 8, 23, 0),
		}, {
			id: 'o',
			type: 0,
			content: '你好',
			timeStamp: new Date(2020, 7, 9, 12, 49, 0),
		}, {
			id: 'a',
			type: 0,
			content: '你好呀！',
			timeStamp: new Date(2019, 6, 12, 12, 49, 0),
		}]
	},
	// 新朋友
	newFriends() {
		return [{
			id: 'a',
			avatar: '1.jpg',
			nickname: '岛上书店_(:з」∠)_',
			desc: '哈哈哈哈哈哈哈哈哈哈或或或或或或或或或或或或或或'
		}, {
			id: 'b',
			avatar: '2.jpg',
			nickname: 'aaa',
			desc: 'aasddasadsadasdadsadsadasdasdsadasdddddddadsa'
		}, {
			id: 'c',
			avatar: '3.jpg',
			nickname: 'aaa',
			desc: 'a啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊'
		}, {
			id: 'd',
			avatar: '4.jpg',
			nickname: 'aaa',
			desc: 'a啊啊啊啊啊'
		}]
	},
	// 搜索
	search() {
		return [{
			type: 1,
			name: '联系人',
			results: [{
				id: 'a',
				avatar: '1.jpg',
				nickname: 'Linda',
				noteName: '小姐姐',
				desc: '三生三世'
			}, {
				id: 'b',
				avatar: '2.jpg',
				nickname: '猪小艾',
				noteName: '',
				desc: 'vssvsvsvvssvsvsvvssvsvsvvssvsvsvvssvsvsvvssvsvsvvssvsvsvvssvsvsv'
			}, {
				id: 'c',
				avatar: '3.jpg',
				nickname: '苏研研',
				noteName: '',
				desc: '是飒飒撒发顺丰撒发生大萨达撒方式方法撒是飒飒撒发顺丰撒发生大萨达撒方式方法撒是飒飒撒发顺丰撒发生大萨达撒方式方法撒'
			}, {
				id: 'd',
				avatar: '4.jpg',
				nickname: '苏皓',
				noteName: '皓皓',
				desc: 'dsvfghjjhgdfs.....'
			}]
		}, {
			type: 2,
			name: '群聊',
			results: [{
				id: 'a',
				name: 'OUZERO',
				avatar: '3.jpg',
				topping: true,
				founderId: 'o',
				isManager: true
			}, {
				id: 'b',
				name: '哈哈哈',
				avatar: '4.jpg',
				founderId: 'a',
				topping: true,
				isManager: false
			}, {
				id: 'c',
				name: '恍恍惚惚',
				avatar: '5.jpg',
				founderId: 'b',
				topping: false,
				isManager: true
			}]
		}]
	}
}
